environment:
  matrix:
  - ARCH: "i686"
  - ARCH: "x86_64"

matrix:
  allow_failures:
    - ARCH: "i686"

init:
# Carriage returns are bad
  - git config --global core.autocrlf input

build_script:
# Remove C:\MinGW\bin from the path, the version of MinGW installed on
# AppVeyor is not compatible with the cross-compiled Julia Windows binaries
  - set PATH=%PATH:C:\MinGW\bin;=%
# Since the AppVeyor VMs have Git installed, they have MSYS1
  - sh --login /c/projects/julia/contrib/windows/msys_build.sh

test_script:
  - set JULIA_CPU_CORES=4
  - cd test && ..\usr\bin\julia runtests.jl all
