install:
  - cinst cyg-get
  - set PATH=%PATH%;C:\cygwin
  - cyg-get make
  - cyg-get git
  - cyg-get wget
  - cyg-get mingw64-x86_64-gcc-g++
  - cyg-get mingw64-x86_64-gcc-fortran

build_script:
  C:\cygwin\bin\sh.exe -o igncr contrib/cygwin_build.sh
