install:
  - cinst cyg-get
  - set PATH=%PATH%;C:\cygwin
  - cyg-get dos2unix
  - cyg-get make
  - cyg-get wget
  - cyg-get mingw64-x86_64-gcc-g++
  - cyg-get mingw64-x86_64-gcc-fortran

build_script:
  C:\cygwin\bin\sh.exe --login -c "cd /cygdrive/c/projects/julia && dos2unix contrib/cygwin_build.sh 2>/dev/null && contrib/cygwin_build.sh"
