environment:
  matrix:
  - JULIAVERSION: "win32"
#  - JULIAVERSION: "win64"

clone_depth: 50

install:
#  - ps: (Get-WMIObject Win32_PhysicalMemory | Measure-Object Capacity -Sum).sum
#  - ps: (Get-Counter '\Memory\Available Bytes')
#  - ps: (Get-Counter '\Memory\% Committed Bytes In Use')
#  - ps: (Get-Process | Sort-Object -Descending WS)
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile($("http://status.julialang.org/download/"+$env:JULIAVERSION), "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia-binary
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia-binary
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%

build_script:
#  - ps: (Get-WMIObject Win32_PhysicalMemory | Measure-Object Capacity -Sum).sum
#  - ps: (Get-Counter '\Memory\Available Bytes')
#  - ps: (Get-Counter '\Memory\% Committed Bytes In Use')
#  - where sh.exe
#  - set OPENBLAS_CORETYPE=opteron
  - C:\projects\julia-binary\bin\julia -e "versioninfo()"
  - cd test && C:\projects\julia-binary\bin\julia runtests.jl all
