install:
  - cinst 7zip
# download most-recent Julia binary for dependencies
  - ps: (new-object net.webclient).DownloadFile('http://s3.amazonaws.com/julialang/bin/winnt/x64/0.3/julia-0.3.0-prerelease-win64.exe', 'julia-prev.exe')
# extract installer
  - 7z x C:\projects\julia\julia-prev.exe
# run installer silently, output to C:\projects\julia-prev
  - julia-installer.exe /S /D=C:\projects\julia-prev
# copy dll's from julia-prev/bin to julia/usr/bin
  - mkdir C:\projects\julia\usr\bin
  - copy C:\projects\julia-prev\bin\*.dll C:\projects\julia\usr\bin
# install Cygwin and build-time dependencies
  - "cinst cyg-get > cyg-get.log"
  - set PATH=%PATH%;C:\cygwin
  - "cyg-get dos2unix >> cyg-get.log"
  - "cyg-get make >> cyg-get.log"
  - "cyg-get wget >> cyg-get.log"
  - "cyg-get bsdtar >> cyg-get.log"
  - "cyg-get mingw64-x86_64-gcc-g++ >> cyg-get.log"
  - "cyg-get mingw64-x86_64-gcc-fortran >> cyg-get.log"

build_script:
  C:\cygwin\bin\sh.exe --login -c "cd /cygdrive/c/projects/julia && dos2unix contrib/cygwin_build.sh 2>&1 && contrib/cygwin_build.sh"
