environment:
  matrix:
#  - ARCH: "i686"
  - ARCH: "x86_64"

init:
# Carriage returns are bad
  - git config --global core.autocrlf input

build_script:
# Since the AppVeyor VMs have Git installed, they have MSYS1
  - sh --login /c/projects/julia/contrib/windows/msys_build.sh

test_script:
  - cd test && ..\usr\bin\julia-basic runtests.jl all
