install:
  - "cinst cyg-get > cyg-get.log"
  - set PATH=%PATH%;C:\cygwin
  - "cyg-get dos2unix >> cyg-get.log"
  - "cyg-get make >> cyg-get.log"
  - "cyg-get wget >> cyg-get.log"
  - "cyg-get bsdtar >> cyg-get.log"
  - "cyg-get git >> cyg-get.log"
  - "cyg-get mingw64-x86_64-gcc-g++ >> cyg-get.log"
  - "cyg-get mingw64-x86_64-gcc-fortran >> cyg-get.log"

build_script:
  C:\cygwin\bin\sh.exe --login -c "cd /cygdrive/c/projects/julia && dos2unix contrib/cygwin_build.sh 2>&1 && contrib/cygwin_build.sh"
