environment:
  matrix:
#  - ARCH: "i686"
  - ARCH: "x86_64"

os: Windows Server 2012 R2

init:
# Carriage returns are bad
  - git config --global core.autocrlf input

build_script:
# Remove C:\MinGW\bin from the path, the version of MinGW installed on
# AppVeyor is not compatible with the cross-compiled Julia Windows binaries
  - set PATH=%PATH:C:\MinGW\bin;=%
  - sh --login /c/projects/julia/contrib/windows/msys_build.sh
#  - cd base
#  - ..\usr\bin\julia --build C:\projects\julia\usr\lib\julia\sys0 sysimg.jl
#  - ..\usr\bin\julia --build C:\projects\julia\usr\lib\julia\sys -JC:\projects\julia\usr\lib\julia\sys0.ji -f sysimg.jl
#  - cd ..

test_script:
#  - set JULIA_CPU_CORES=4
  - cd test && ..\usr\bin\julia runtests.jl core keywordargs numbers strings collections hashing remote iobuffer arrayops simdloop blas fft dsp sparse bitarray random math functional bigint sorting statistics spawn priorityqueue arpack file suitesparse version resolve pollfd mpfr broadcast complex socket floatapprox readdlm regex float16 combinatorics sysinfo rounding ranges mod2pi euler show lineedit replcompletions parallel
