environment:
  HOMEDRIVE: "C:"
  HOMEPATH: \Users\appveyor
  XC_HOST: "i686-pc-mingw32"

install:
  - cinst 7zip
# Download most-recent Julia binary for dependencies
  - ps: "(new-object net.webclient).DownloadFile(IF ($XC_HOST -eq 'i686-pc-mingw32')
    {'http://s3.amazonaws.com/julialang/bin/winnt/x86/0.3/julia-0.3.0-prerelease-win32.exe'}
    ELSE {'http://s3.amazonaws.com/julialang/bin/winnt/x64/0.3/julia-0.3.0-prerelease-win64.exe'},
    C:\projects\julia-prev.exe)"
# Extract installer, run it silently, output to C:\projects\julia-prev
  - 7z x C:\projects\julia-prev.exe -oC:\projects\julia-prev
  - C:\projects\julia-prev\julia-installer.exe /S /D=C:\projects\julia-prev
# Copy dll's and libuv includes from julia-prev to julia/usr
  - mkdir C:\projects\julia\usr\bin
  - copy C:\projects\julia-prev\bin\*.dll C:\projects\julia\usr\bin
# Uncomment these once Windows binaries get updated with latest version of libuv
#  - mkdir C:\projects\julia\usr\include
#  - copy C:\projects\julia-prev\include\julia\uv*.h C:\projects\julia\usr\include
#  - copy C:\projects\julia-prev\include\julia\tree.h C:\projects\julia\usr\include
# Install Cygwin and build-time dependencies
  - "cinst cyg-get > cyg-get.log"
  - set PATH=%PATH%;C:\cygwin
  - "cyg-get make >> cyg-get.log"
  - "cyg-get wget >> cyg-get.log"
  - "cyg-get bsdtar >> cyg-get.log"
  - ps: "IF ($XC_HOST -eq 'i686-pc-mingw32')
    {cyg-get mingw64-i686-gcc-g++ >> cyg-get.log}
    ELSE {cyg-get mingw64-x86_64-gcc-g++ >> cyg-get.log}"
# python, gcc-g++, and diffutils are required to build llvm from source
#  - "cyg-get python >> cyg-get.log"
#  - "cyg-get gcc-g++ >> cyg-get.log"
#  - "cyg-get diffutils >> cyg-get.log"
# mingw64-x86_64-gcc-fortran is required to build openblas, arpack, etc from source
#  - "cyg-get mingw64-x86_64-gcc-fortran >> cyg-get.log"

build_script:
  - C:\cygwin\bin\sh.exe --login -c "cd /cygdrive/c/projects/julia && sh -o igncr contrib/cygwin_build.sh 2>&1"

test_script:
  - cd test && ..\usr\bin\julia-readline runtests.jl all
