environment:
  matrix:
#  - ARCH: "i686"
  - ARCH: "x86_64"

init:
# Carriage returns are bad
  - git config --global core.autocrlf input

#install:
# Install Cygwin and build-time dependencies
#  - "cinst cyg-get > cyg-get.log"
#  - set PATH=%PATH%;C:\cygwin
#  - "cyg-get make >> cyg-get.log"
#  - "cyg-get curl >> cyg-get.log"
#  - "cyg-get mingw64-%ARCH%-gcc-g++ >> cyg-get.log"

build_script:
  - sh --login /c/projects/julia/contrib/windows/msys_build.sh

test_script:
  - set JULIA_CPU_CORES=4
  - cd test && ..\usr\bin\julia runtests.jl all
