install:
  - cinst cyg-get
  - set PATH=%PATH%;C:\cygwin
  - cyg-get default,mingw64-x86_64-gcc-g++,mingw64-x86_64-gcc-gfortran

build_script:
  C:\cygwin\bin\sh.exe --login -c "cd /cygdrive/c/projects/julia; pwd; uname -a; ls; make XC_HOST=x86_64-w64-mingw32"
