version: 2.0
jobs:
  build:
    docker:
      - image: ubuntu:14.04
#      - image: circleci/python:2.7
#    resource_class: xlarge
    steps:
      - run: apt-get update
      - run: apt-get install -y wget make patch m4 xz-utils
             git g++-multilib gfortran-multilib ccache
      - checkout
      - run: date +%Y%W > /tmp/weeknumber
      - restore_cache:
          keys:
            - ccache-{{ checksum "/tmp/weeknumber" }}
      - run: contrib/download_cmake.sh
      - run: make -j8 -C deps USECCACHE=1 || make USECCACHE=1
      - run: ccache -s
      - run: make -j8 all && make install
      - run: ./julia -e 'versioninfo()'
      - run: JULIA_CPU_CORES=4 make -j8 testall test-libgit2-online test-download test-pkg
      - save_cache:
          key: ccache-{{ checksum "/tmp/weeknumber" }}
          paths:
            - ~/.ccache
