version: 2.0
jobs:
  build:
    docker:
#      - image: ubuntu:14.04
      - image: circleci/python:2.7
#    resource_class: xlarge
    steps:
      - checkout
      - run: nproc
      - run: uname -a
      - run: cat /etc/os-release
      - run: sudo apt-get install -y gfortran
#      - run: apt-get install -y wget make patch m4 xz-utils g++ gfortran
      - run: contrib/download_cmake.sh
      - run: make -j2 -C deps || make
      - run: make -j2 all install
