version: 2
workflows:
  version: 2
  builds:
    jobs:
      - build-x86_64
      - build-i686

jobs:
  build-x86_64:
    docker:
      - image: ubuntu:14.04
#      - image: circleci/python:2.7
        environment:
          JULIA_CPU_CORES: 8
          ARCH: x86_64
#    resource_class: xlarge
    steps: &steps
      - run: apt-get update
      - run: apt-get install -y wget make patch m4 xz-utils
             git g++-multilib gfortran-multilib ccache
      - checkout
      - run: echo "$HOME $(date +%Y%W)" | tee /tmp/weeknumber
      - restore_cache:
          keys:
            - ccache-{{ checksum "/tmp/weeknumber" }}
      - run: contrib/download_cmake.sh
      - run: make -j$JULIA_CPU_CORES -C deps USECCACHE=1 || make USECCACHE=1
      - run: ccache -s
      - run: make -j$JULIA_CPU_CORES all && make install
      - run: ./julia -e 'versioninfo()'
      - run: make -j$JULIA_CPU_CORES testall test-libgit2-online test-download test-pkg
      - save_cache:
          key: ccache-{{ checksum "/tmp/weeknumber" }}
          paths:
            - ~/.ccache

  build-i686:
    docker:
      - image: ubuntu:14.04
#      - image: circleci/python:2.7
        environment:
          JULIA_CPU_CORES: 8
          ARCH: i686
#    resource_class: xlarge
    steps: *steps
