jobs:
  build:
    docker:
      - image: ubuntu:14.04

test:
  override:
    - uname -a
    - cat /etc/os-release
    - cmake --version
    - gfortran --version
    - make -j`nproc` -C deps
    - make -j`nproc`
