version: 2.0
jobs:
  build:
    docker:
      - image: ubuntu:14.04
    steps:
      - checkout
#      - run: uname -a
#      - run: cat /etc/os-release
      - run: apt-get update
      - run: apt-get install -y wget make patch gfortran
      - run: contrib/download_cmake.sh
      - run: make -j`nproc` -C deps || make
      - run: make -j`nproc`
