version: 2.0
jobs:
  build:
    docker:
      - image: ubuntu:14.04
#      - image: circleci/python:2.7
#    resource_class: xlarge
    steps:
      - run: apt-get update
      - run: apt-get install -y wget make patch m4 xz-utils git
             ca-certificates g++-multilib gfortran-multilib ccache
      - run: export WEEK=$(date +%Y%W)
      - checkout
      - restore_cache:
          keys:
            - ccache-{{ .Environment.WEEK }}
      - run: contrib/download_cmake.sh
      - run: make -j`nproc` -C deps USECCACHE=1 || make USECCACHE=1
      - run: ccache -s
      - run: make -j`nproc` all && make install
      - run: ./julia -e 'versioninfo()'
      - run: make -j`nproc` testall test-libgit2-online test-download test-pkg
      - save_cache:
          key: ccache-{{ .Environment.WEEK }}
          paths:
            - ~/.ccache
