version: 2.0
jobs:
  build:
    docker:
      - image: ubuntu:14.04
#      - image: circleci/python:2.7
#    resource_class: xlarge
    steps:
      - run: apt-get update
      - run: apt-get install -y wget make patch m4 xz-utils
             git ccache g++-multilib gfortran-multilib
      - checkout
      - restore_cache:
          keys:
            - ccache
      - run: contrib/download_cmake.sh
      - run: make -j8 -C deps USECCACHE=1 || make USECCACHE=1
      - run: make -j8 all && make install
      - run: make -j8 testall test-libgit2-online test-download test-pkg
      - save_cache:
          key: ccache
          paths:
            - ~/.ccache
