version: 2
workflows:
  version: 2
  builds:
    jobs:
      - build-x86_64
      - build-i686

jobs:
  build-x86_64:
    docker:
      - image: ubuntu:14.04
#      - image: circleci/python:2.7
        environment:
          JULIA_CPU_CORES: 6
          ARCH: x86_64
#    resource_class: xlarge
    steps: &steps
      - run: | # install build dependencies
          apt-get update &&
          apt-get install -y curl make patch m4 xz-utils \
             git g++-multilib gfortran-multilib time ccache
      - checkout # magic circle ci code checkout step
      - run: | # set versioning info and Make.user variables
          make -C base version_git.jl.phony &&
          echo "override ARCH = $ARCH" | tee -a Make.user &&
          for var in FORCE_ASSERTIONS LLVM_ASSERTIONS USECCACHE NO_GIT; do
            echo "override $var = 1" | tee -a Make.user;
          done &&
          echo "$ARCH $HOME $(date +%Y%W)" | tee /tmp/weeknumber
      - restore_cache: # silly to take a checksum of the tag file here instead of
          keys: # its contents but this is the only thing that works on circle
            - ccache-{{ checksum "/tmp/weeknumber" }}
      - run: | # build deps, output ccache stats when done
          contrib/download_cmake.sh &&
          make -j8 -C deps || make;
          ccache -s
      - run: | # build julia
          make -j8 all &&
          make prefix=/tmp/julia install &&
          make build-stats &&
          /tmp/julia/bin/julia -e 'versioninfo()'
      - run: make -j8 testall test-libgit2-online test-download test-pkg
      - save_cache:
          key: ccache-{{ checksum "/tmp/weeknumber" }}
          paths:
            - ~/.ccache

  build-i686:
    docker:
      - image: ubuntu:14.04
#      - image: circleci/python:2.7
        environment:
          JULIA_CPU_CORES: 6
          ARCH: i686
#    resource_class: xlarge
    steps: *steps


# how travis runs the tests:
#    - cd .. && mv julia julia2
#    - /tmp/julia/bin/julia --precompiled=no -e 'true' &&
#        /tmp/julia/bin/julia-debug --precompiled=no -e 'true'
#    - /tmp/julia/bin/julia -e 'versioninfo()'
#    - pushd /tmp/julia/share/julia/test
#    - export JULIA_CPU_CORES=2 && export JULIA_TEST_MAXRSS_MB=600 &&
#        /tmp/julia/bin/julia --check-bounds=yes runtests.jl $TESTSTORUN &&
#        /tmp/julia/bin/julia --check-bounds=yes runtests.jl libgit2-online download pkg
#    - popd
    # test that the embedding code works on our installation
#    - mkdir /tmp/embedding-test &&
#        make check -C /tmp/julia/share/doc/julia/examples/embedding \
#             JULIA="DYLD_FALLBACK_LIBRARY_PATH='$DYLD_FALLBACK_LIBRARY_PATH' /tmp/julia/bin/julia" \
#             BIN=/tmp/embedding-test \
#             "$(cd julia2 && make print-CC)"
#    - mv julia2 julia &&
#after_success:
#    - cd julia && make -C doc deploy
