version: 2.0
jobs:
  build:
    docker:
      - image: ubuntu:14.04
    steps:
      - checkout
      - run: uname -a
      - run: cat /etc/os-release
      - run: cmake --version
      - run: gfortran --version
      - run: make -j`nproc` -C deps
      - run: make -j`nproc`
